/**
 * Hint Engine Service
 * 
 * Implements a 3-level graduated hint system from the research paper:
 * - Level 1: General direction — nudges the learner toward the right area
 * - Level 2: Specific guidance — points to the specific concept or data
 * - Level 3: Direct explanation — provides detailed clinical reasoning (LLM-generated in future)
 * 
 * Hints escalate when the same error type persists after a hint is given.
 */

import type { ErrorClassification, ErrorType } from './errorDetector';

// ============================================
// Types
// ============================================

export type HintLevel = 1 | 2 | 3;

export interface Hint {
    /** Escalation level (1 = subtle, 2 = specific, 3 = direct) */
    level: HintLevel;
    /** Display message for the learner */
    message: string;
    /** Whether this is an error correction vs. a learning opportunity */
    isErrorCorrection: boolean;
    /** The error type that triggered this hint */
    errorType: ErrorType;
    /** Suggested action ID if applicable (e.g., the correct alternative) */
    suggestedActionId?: string;
}

export interface HintState {
    /** Current hint level per error type */
    levels: Record<ErrorType, number>;
    /** Total hints given in this session */
    totalHintsGiven: number;
    /** History of hints given */
    history: Array<{ hint: Hint; timestamp: number }>;
}

// ============================================
// Hint Templates
// ============================================

/**
 * Templates for each error type at each hint level.
 * Level 3 templates serve as fallbacks; in production, L3 hints
 * should be generated by the LLM (ECA service) for richer context.
 */
const HINT_TEMPLATES: Record<ErrorType, Record<HintLevel, string>> = {
    hesitation: {
        1: 'Take a moment to review the available patient information. What stands out to you?',
        2: 'Look at the patient\'s vital signs and symptoms — they may guide your next action. What patterns do you notice?',
        3: 'Based on the current clinical picture, consider starting with the most informative diagnostic test. Prioritize actions that will narrow down the differential diagnosis.',
    },
    premature_closure: {
        1: 'Before proceeding with treatment, are you confident you have enough information?',
        2: 'Important diagnostic information may still be missing. Review which tests or assessments haven\'t been performed yet.',
        3: 'You\'ve only completed a limited diagnostic workup. In clinical practice, premature treatment decisions can lead to missed diagnoses. Consider gathering more data before committing to a treatment plan.',
    },
    syntax: {
        1: 'Think about what type of action would be most appropriate at this point in the case.',
        2: 'At this stage, you may want to focus on gathering information rather than intervening. What diagnostic steps are still available?',
        3: 'The current clinical situation calls for a different approach. Review the stage objectives and consider which category of actions (diagnostic vs. therapeutic) would be most beneficial right now.',
    },
    semantic: {
        1: 'Consider the potential consequences of this action on the patient\'s condition.',
        2: 'Review the patient\'s current status carefully. This action might not be appropriate given their clinical state.',
        3: 'This action could worsen the patient\'s condition. Consider the underlying pathophysiology and how this intervention would interact with the current clinical picture. An alternative approach may be safer.',
    },
};

// ============================================
// Core Functions
// ============================================

/**
 * Create a fresh hint state for a new simulation session.
 */
export function createHintState(): HintState {
    return {
        levels: {
            syntax: 0,
            semantic: 0,
            hesitation: 0,
            premature_closure: 0,
        },
        totalHintsGiven: 0,
        history: [],
    };
}

/**
 * Generate a hint for a detected error, respecting the current escalation level.
 * Each call for the same error type escalates the hint level (up to 3).
 */
export function getHint(
    error: ErrorClassification,
    state: HintState
): { hint: Hint; updatedState: HintState } {
    const currentLevel = state.levels[error.type] || 0;
    const nextLevel = Math.min(currentLevel + 1, 3) as HintLevel;

    const message = HINT_TEMPLATES[error.type]?.[nextLevel]
        || 'Review the available information and consider your options carefully.';

    const hint: Hint = {
        level: nextLevel,
        message,
        isErrorCorrection: error.severity === 'high',
        errorType: error.type,
    };

    const updatedState: HintState = {
        levels: {
            ...state.levels,
            [error.type]: nextLevel,
        },
        totalHintsGiven: state.totalHintsGiven + 1,
        history: [...state.history, { hint, timestamp: Date.now() }],
    };

    return { hint, updatedState };
}

/**
 * Check whether the hint level should escalate for a given error type.
 * Returns true if the error persists and the level hasn't maxed out.
 */
export function shouldEscalate(
    errorType: ErrorType,
    state: HintState
): boolean {
    const currentLevel = state.levels[errorType] || 0;
    return currentLevel < 3;
}

/**
 * Reset the hint level for a specific error type.
 * Called when the learner corrects their error after receiving a hint.
 */
export function resetErrorHintLevel(
    errorType: ErrorType,
    state: HintState
): HintState {
    return {
        ...state,
        levels: {
            ...state.levels,
            [errorType]: 0,
        },
    };
}

/**
 * Get summary statistics for the hint session.
 */
export function getHintStats(state: HintState) {
    const hintsByType: Record<ErrorType, number> = {
        syntax: 0,
        semantic: 0,
        hesitation: 0,
        premature_closure: 0,
    };

    for (const entry of state.history) {
        hintsByType[entry.hint.errorType]++;
    }

    const maxLevelReached = Math.max(
        ...Object.values(state.levels),
        0
    );

    return {
        totalHints: state.totalHintsGiven,
        hintsByType,
        maxLevelReached,
        currentLevels: { ...state.levels },
    };
}

/**
 * Format a hint for display, adding contextual prefix based on level.
 */
export function formatHintForDisplay(hint: Hint): {
    title: string;
    message: string;
    icon: 'info' | 'warning' | 'alert';
} {
    const levelConfig: Record<HintLevel, { title: string; icon: 'info' | 'warning' | 'alert' }> = {
        1: { title: '💡 Consider...', icon: 'info' },
        2: { title: '⚡ Guidance', icon: 'warning' },
        3: { title: '📋 Clinical Note', icon: 'alert' },
    };

    const config = levelConfig[hint.level];

    return {
        title: config.title,
        message: hint.message,
        icon: config.icon,
    };
}
