/**
 * Question Engine
 * 
 * Generates dynamic what-if questions from learner traces using a hybrid approach:
 * - Rule-based generation (instant, zero latency) as base
 * - LLM generation (async via Edge Function) to augment with causal reasoning chains
 * 
 * The rule-based layer always fires immediately. LLM responses are requested
 * asynchronously and replace/augment rule-based scenarios when they arrive.
 */

import type {
    SimulationDecision,
    BranchingCase,
    SimulationStage,
    PatientState,
} from '@/types/simulation';
import type { WhatIfScenario } from '@/types/analytics';
import type { DigitalTrace, WhatQuestion, CognitiveLevel } from '@/types/domainModel';
import { generateWhatIfScenarios } from '@/services/whatIfService';
import { supabase } from '@/integrations/supabase/client';

// ======================
// Types
// ======================

export interface CausalStep {
    action: string;
    consequence: string;
    probability: 'high' | 'medium' | 'low';
}

export interface EnhancedWhatIfScenario extends WhatIfScenario {
    /** Reasoning chain explaining why the alternative leads to this outcome */
    causalChain?: CausalStep[];
    /** Clinical reasoning question to prompt reflection */
    reflectionQuestion?: string;
    /** Whether this was generated by the LLM or rule engine */
    source: 'rule-based' | 'llm';
    /** Confidence score (0-1) for LLM-generated scenarios */
    confidence?: number;
}

export interface QuestionContext {
    caseData: BranchingCase;
    currentStage: SimulationStage;
    patientState: PatientState;
    decisionsLog: Array<{
        decision: SimulationDecision;
        timestamp: Date;
        stageId: string;
    }>;
    sessionId: string;
}

// ======================
// Cache for LLM responses
// ======================

const responseCache = new Map<string, { scenarios: EnhancedWhatIfScenario[]; timestamp: number }>();
const CACHE_TTL_MS = 60 * 60 * 1000; // 1 hour

function getCacheKey(decisionId: string, stageId: string): string {
    return `${decisionId}__${stageId}`;
}

function getCachedResponse(key: string): EnhancedWhatIfScenario[] | null {
    const entry = responseCache.get(key);
    if (entry && Date.now() - entry.timestamp < CACHE_TTL_MS) {
        return entry.scenarios;
    }
    responseCache.delete(key);
    return null;
}

function setCachedResponse(key: string, scenarios: EnhancedWhatIfScenario[]): void {
    responseCache.set(key, { scenarios, timestamp: Date.now() });
}

// ======================
// Core Functions
// ======================

/**
 * Generate enhanced what-if scenarios synchronously (rule-based).
 * Returns immediately with rule-based scenarios.
 */
export function generateRuleBasedScenarios(
    decision: SimulationDecision,
    context: QuestionContext,
): EnhancedWhatIfScenario[] {
    const baseScenarios = generateWhatIfScenarios(
        decision,
        context.caseData,
        context.currentStage,
    );

    return baseScenarios.map(scenario => ({
        ...scenario,
        source: 'rule-based' as const,
        reflectionQuestion: generateReflectionQuestion(decision, scenario, context),
        causalChain: generateRuleBasedCausalChain(decision, scenario, context),
    }));
}

/**
 * Generate LLM-enhanced scenarios asynchronously.
 * Falls back silently if the Edge Function is unavailable.
 */
export async function generateLLMScenarios(
    decision: SimulationDecision,
    context: QuestionContext,
    existingScenarios: EnhancedWhatIfScenario[],
): Promise<EnhancedWhatIfScenario[]> {
    const cacheKey = getCacheKey(decision.id, context.currentStage.id);
    const cached = getCachedResponse(cacheKey);
    if (cached) return cached;

    try {
        const { data, error } = await supabase.functions.invoke('eca-chat', {
            body: {
                message: buildLLMPrompt(decision, context, existingScenarios),
                conversationHistory: [],
                context: {
                    caseTitle: context.caseData.title,
                    specialty: context.caseData.specialty,
                    currentStage: context.currentStage.name || context.currentStage.id,
                    patientStatus: context.patientState.status,
                    vitalSigns: context.patientState.vitalSigns,
                    recentDecisions: context.decisionsLog.slice(-5).map(d => d.decision.label),
                    errorsDetected: [],
                    hintLevel: 0,
                    decisionsCount: context.decisionsLog.length,
                    timeElapsed: context.patientState.timeElapsed,
                },
                sessionId: context.sessionId,
            },
        });

        if (error) {
            console.warn('LLM scenario generation failed, using rule-based only:', error);
            return existingScenarios;
        }

        // Parse LLM response
        const llmScenarios = parseLLMResponse(data, decision, existingScenarios);
        const combined = mergeScenarios(existingScenarios, llmScenarios);

        setCachedResponse(cacheKey, combined);
        return combined;
    } catch (err) {
        console.warn('LLM scenario generation error:', err);
        return existingScenarios;
    }
}

/**
 * Full generation pipeline: rule-based first, then LLM async.
 * Returns rule-based immediately, calls onUpdate when LLM finishes.
 */
export function generateEnhancedScenarios(
    decision: SimulationDecision,
    context: QuestionContext,
    onUpdate: (scenarios: EnhancedWhatIfScenario[]) => void,
): EnhancedWhatIfScenario[] {
    // 1. Rule-based (instant)
    const ruleBasedScenarios = generateRuleBasedScenarios(decision, context);

    // 2. LLM (async, fire-and-forget)
    generateLLMScenarios(decision, context, ruleBasedScenarios)
        .then(enhanced => {
            if (enhanced !== ruleBasedScenarios) {
                onUpdate(enhanced);
            }
        })
        .catch(() => {
            // Silently fail — rule-based scenarios are sufficient
        });

    return ruleBasedScenarios;
}

// ======================
// UML Domain Model Extensions
// ======================

/**
 * Analyze digital traces to generate targeted what-questions.
 * UML: QuestionEngine.analyzeTraces()
 */
export function analyzeTraces(trace: DigitalTrace): string[] {
    const insights: string[] = [];

    // Analyze errors
    if (trace.errors.length > 0) {
        insights.push(`Detected ${trace.errors.length} errors.`);
    }

    // Analyze time
    if (trace.timeSpent > 120 && trace.errors.length === 0) {
        insights.push('Learner is calculating carefully.');
    } else if (trace.timeSpent < 10 && trace.errors.length > 0) {
        insights.push('Learner is rushing.');
    }

    return insights;
}

/**
 * Generate a structured WhatQuestion based on analysis.
 * UML: QuestionEngine.generateWhatQuestion()
 */
export function generateWhatQuestion(
    trace: DigitalTrace,
    context: QuestionContext
): WhatQuestion | null {
    // Example logic:
    // If learner made a semantic error, generate an "Evaluate" level question
    const hasSemanticError = trace.errors.some(e => e.includes('semantic'));

    if (hasSemanticError) {
        return {
            cognitiveLevel: 'evaluate',
            clinicalFocus: 'treatment_safety',
            hintLevel: 2,
            question: "What might be the physiological consequence of this intervention given the patient's low BP?",
            alternativeDecisionId: 'fluid_bolus_id' // Hypothetical
        };
    }

    return null;
}

// ======================
// Rule-Based Helpers
// ======================

function generateReflectionQuestion(
    decision: SimulationDecision,
    scenario: WhatIfScenario,
    context: QuestionContext,
): string {
    const questions: Record<string, string[]> = {
        better: [
            `Why might "${scenario.alternative_decision_label}" have led to a better outcome than "${decision.label}"?`,
            `What clinical reasoning supports choosing "${scenario.alternative_decision_label}" at this stage?`,
            `How would the patient's trajectory change if you had opted for "${scenario.alternative_decision_label}"?`,
        ],
        worse: [
            `What makes "${decision.label}" a better choice than "${scenario.alternative_decision_label}" in this context?`,
            `What risks are associated with "${scenario.alternative_decision_label}" for this patient?`,
            `Can you identify the clinical evidence that supports your decision of "${decision.label}"?`,
        ],
        similar: [
            `Both options could work here. What factors would help you distinguish between them?`,
            `In what clinical circumstances would "${scenario.alternative_decision_label}" become clearly preferable?`,
            `What additional information would help you confidently choose between these options?`,
        ],
    };

    const outcomeQuestions = questions[scenario.predicted_outcome] || questions['similar'];
    return outcomeQuestions[Math.floor(Math.random() * outcomeQuestions.length)];
}

function generateRuleBasedCausalChain(
    decision: SimulationDecision,
    scenario: WhatIfScenario,
    context: QuestionContext,
): CausalStep[] {
    const chain: CausalStep[] = [];
    const alt = scenario.alternative_decision_label || scenario.alternative_decision;

    // Step 1: Action taken
    chain.push({
        action: `Choose "${alt}" instead of "${decision.label}"`,
        consequence: scenario.predicted_outcome === 'better'
            ? 'May address the clinical priority more directly'
            : scenario.predicted_outcome === 'worse'
                ? 'Could miss a critical diagnostic or treatment step'
                : 'Provides similar clinical information',
        probability: scenario.predicted_outcome === 'similar' ? 'high' : 'medium',
    });

    // Step 2: Patient impact
    if (scenario.predicted_outcome === 'better') {
        chain.push({
            action: 'Earlier identification of key findings',
            consequence: 'Patient receives more targeted care sooner',
            probability: 'medium',
        });
    } else if (scenario.predicted_outcome === 'worse') {
        chain.push({
            action: 'Delayed or missed critical information',
            consequence: 'Risk of patient deterioration or delayed treatment',
            probability: 'medium',
        });
    }

    // Step 3: Learning outcome
    chain.push({
        action: 'Reflect on this decision point',
        consequence: 'Understanding helps improve future clinical reasoning',
        probability: 'high',
    });

    return chain;
}

// ======================
// LLM Helpers
// ======================

function buildLLMPrompt(
    decision: SimulationDecision,
    context: QuestionContext,
    existingScenarios: EnhancedWhatIfScenario[],
): string {
    const alts = existingScenarios.map(s => s.alternative_decision_label).join(', ');
    return `Generate enhanced what-if analysis for this clinical decision.

DECISION MADE: "${decision.label}" (${decision.type})
ALTERNATIVES CONSIDERED: ${alts || 'None identified'}
PATIENT STATUS: ${context.patientState.status}
STAGE: ${context.currentStage.name || context.currentStage.id}

For each alternative, provide:
1. A detailed causal chain (3-4 steps) showing how this choice affects patient outcome
2. A reflective question that promotes deeper clinical reasoning
3. A confidence score (0-1) for the predicted outcome

Return as JSON array of objects with: alternative_id, causal_chain [{action, consequence, probability}], reflection_question, confidence`;
}

function parseLLMResponse(
    data: any,
    decision: SimulationDecision,
    existingScenarios: EnhancedWhatIfScenario[],
): EnhancedWhatIfScenario[] {
    if (!data?.response) return [];

    try {
        const content = typeof data.response === 'string' ? data.response : JSON.stringify(data.response);
        const cleaned = content.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
        const parsed = JSON.parse(cleaned);

        if (!Array.isArray(parsed)) return [];

        return parsed.map((item: any) => {
            const matching = existingScenarios.find(s => s.alternative_decision === item.alternative_id);
            return {
                ...(matching || existingScenarios[0]),
                causalChain: item.causal_chain || [],
                reflectionQuestion: item.reflection_question || '',
                source: 'llm' as const,
                confidence: item.confidence || 0.7,
            };
        }).filter(Boolean);
    } catch {
        return [];
    }
}

function mergeScenarios(
    ruleBased: EnhancedWhatIfScenario[],
    llm: EnhancedWhatIfScenario[],
): EnhancedWhatIfScenario[] {
    if (llm.length === 0) return ruleBased;

    // Merge: for each rule-based scenario, replace with LLM version if available
    return ruleBased.map(rb => {
        const llmVersion = llm.find(l => l.alternative_decision === rb.alternative_decision);
        if (llmVersion) {
            return {
                ...rb,
                causalChain: llmVersion.causalChain,
                reflectionQuestion: llmVersion.reflectionQuestion || rb.reflectionQuestion,
                source: 'llm' as const,
                confidence: llmVersion.confidence,
            };
        }
        return rb;
    });
}
